// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCSGNl9MyCH6GQUOJGCLjo3jn6f88O2Q',
    appId: '1:673586780607:android:f9fa54eef687b11365290a',
    messagingSenderId: '673586780607',
    projectId: 'ai-wallpaper-beb91',
    storageBucket: 'ai-wallpaper-beb91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7zJ_UupUd0vzQd66HHw5jUCqiAg_ew7Y',
    appId: '1:673586780607:ios:02ec17ca78ae83fc65290a',
    messagingSenderId: '673586780607',
    projectId: 'ai-wallpaper-beb91',
    storageBucket: 'ai-wallpaper-beb91.firebasestorage.app',
    androidClientId: '673586780607-ttikvl0et8j8hoqer6stqqjtv16jt37m.apps.googleusercontent.com',
    iosClientId: '673586780607-rikpp5heteksbddbtsovio3khef15b69.apps.googleusercontent.com',
    iosBundleId: 'com.Updesh.AIWallpaper',
  );

}